version: '1.0'
name: pipeline-20220526
displayName: pipeline-20220526
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-cb074ee6
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@docker
        name: build_docker
        displayName: 镜像构建
        type: account
        repository: '111111'
        username: '18792809954'
        password: happydang1215
        tag: ${GITEE_PIPELINE_BUILD_NUMBER}
        dockerfile: ./Dockerfile
        isCache: true
        strategy:
          retry: '0'
permissions:
  - role: admin
    members: []
