name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      id: docker-build
      run: |
        docker build . --file Dockerfile --tag seolhw/my-image-name:$(date +%s)
        echo "::set-output name=tag::$(date +%s)"

    - name: login docker hub
      run: docker login -u seolhw -p dear7758521
    - name: push docker hub
      run: docker push seolhw/my-image-name:$(date +%s)


